version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hemligt
volumes:
  postgresdata:
